### ISSUE TITLE
CFF files generated for articles causes GitHub server to crash

### ISSUE THREAD

**Issue by jeyabbalas** [dieghernan/cffr#44]
Hello,

I am not sure if this is a GitHub issue or a `cffr` issue. 

I tried to generate a CFF file using the `cff_from_bibtex()` method in `cffr`. I follow the example in the manual as below:

```r
if (requireNamespace("bibtex", quietly = TRUE)) {
  x <- c(
    "@article{vaswani2017attention,
  title={Attention is all you need},
  author={Vaswani, Ashish and Shazeer, Noam and Parmar, Niki and Uszkoreit, Jakob and Jones, Llion and Gomez, Aidan N and Kaiser, Lukasz and Polosukhin, Illia},
  journal={Advances in neural information processing systems},
  volume={30},
  year={2017}
}"
  )
}
  
cff_from_bibtex(x)
```

This generated the following text: 

```
type: article
title: Attention is all you need
authors:
- family-names: Vaswani
  given-names: Ashish
- family-names: Shazeer
  given-names: Noam
- family-names: Parmar
  given-names: Niki
- family-names: Uszkoreit
  given-names: Jakob
- family-names: Jones
  given-names: Llion
- family-names: Gomez
  given-names: Aidan N
- family-names: Kaiser
  given-names: Lukasz
- family-names: Polosukhin
  given-names: Illia
journal: Advances in neural information processing systems
volume: '30'
year: '2017'
```

I saved it in a `CITATION.cff` file and pushed it to my GitHub repository. After that, I went to my GitHub repository to view the file and it leads to a server error (status: 500). GitHub is unable to parse this file. When I remove the line `type: article` from the file, this error goes away. However, now, instead of citing an article, GitHub assumes that this citation is of type `software`. Could this be a conflict with CFF specification for articles? GitHub's CFF specification wasn't helpful. So, I was hoping this community was familiar with this issue.

Thank you for all your work!
