### ISSUE TITLE
GitHub rendering issues on CITATION.cff where `preferred-citation:   type: manual`

### ISSUE THREAD

**Issue by dieghernan** [dieghernan/cffr#7]
GitHub is not rendering `CITATION.cff` files properly when `preferred-citation` has `type: manual`:

See [example repo](https://github.com/dieghernan/cfftest/blob/main/CITATION.cff):

```
...
preferred-citation:
  type: manual
  title: 'cffr: Generate Citation File Format (''cff'') Metadata for R Packages'
  authors:
  - family-names: Hernangómez
    given-names: Diego
  year: '2021'
  doi: 10.5281/zenodo.5509766
  url: https://dieghernan.github.io/cffr/
...

```

And the version on [this repo](https://github.com/dieghernan/cffr/blob/main/CITATION.cff):

```
...
preferred-citation:
  type: generic # <<<<< See the difference
  title: 'cffr: Generate Citation File Format (''cff'') Metadata for R Packages'
  authors:
  - family-names: Hernangómez
    given-names: Diego
  year: '2021'
  doi: 10.5281/zenodo.5509766
  url: https://dieghernan.github.io/cffr/
...

```

Not sure where to open this issue, so I just open it here: 

Pinging @sdruskat, @arfon (https://github.com/citation-file-format/citation-file-format/issues/343) and maybe @hainesr
