### ISSUE TITLE
Feature request: Automated generation of `inst/CITATION`

### ISSUE THREAD

**Issue by roaldarbol** [dieghernan/cffr#79]
It would be great to have the option to only maintain the `DESCRIPTION` file and then both the `CITATION.cff` and the `inst/CITATION` files being updated as part of the workflow. As far as I can tell, one will manually have to re-create `inst/CITATION` every time the `CITATION.cff` file is updated. Maybe it is already possible, in which case ignore this.  

Also, along the same lines, it might be helpful having an example of the automated generation solutions in the docs. :-)

**Comment by njtierney** [comment]
Hello! Just seconding that this would be really handy :)

**Comment by dieghernan** [comment]
Hi:

I still have to think about it, since the main purpose of **cffr** is to provide tools for `CITATION.cff` files so I am not very sure of expanding the capabilities beyond that scope. However, the implementation would be fairly easy to do, see:

```r
aa <- cffr::cff_create()
cffr::cff_write(aa)
unlink("inst/CITATION") # Remove already present file
cffr::cff_write_citation(aa, file = "inst/CITATION")
```

And in a github action (see [example](https://github.com/ropensci/cffr/blob/main/.github/workflows/update-citation-cff.yaml)):

```yaml
      - name: Update CITATION.cff
        run: |

          # Customize with your own code
          # See https://docs.ropensci.org/cffr/articles/cffr.html

          # Write your own keys
          mykeys <- list()

          # The object
          cffobj <- cffr::cff_create(keys = mykeys)

          # Create your CITATION.cff file
          cffr::cff_write(cffobj)

          # Update inst/CITATION
          unlink("inst/CITATION")
          cffr::cff_write_citation(cffobj, file = "inst/CITATION")

        shell: Rscript {0}
```
