### ISSUE TITLE
`cff_write(r_citation = TRUE)` does not update existing `inst/CITATION`

### ISSUE THREAD

**Issue by roaldarbol** [dieghernan/cffr#86]
Hey @dieghernan! 
I just tried out the new `r_citation` parameter; unfortunately it doesn't actually seem to update the `CITATION` file. However, if I first delete the file, the correct one is then created. I would expect that it should be updated (as is the intended behaviour I reckon from the parameter description):
```r

r_citation | Logical TRUE/FALSE. On TRUE the R package citation (i.e. inst/CITATION) would be created or updated. No backup copy would be created, for more control use cff_write_citation().
```
---
I attempted with both version updaes and (not shown) changing the actual name of the package, both resulted in the same behaviour. Here's what I did:
```r
> usethis::use_version()
✔ Setting active project to "/Users/roaldarbol/Filen/Projects/R/animovement".
Current version is 0.6.0.
What should the new version be? (0 to exit) 

1: major --> 1.0.0
2: minor --> 0.7.0
3: patch --> 0.6.1
4:   dev --> 0.6.0.9000

Selection: 4
✔ Adding "0.6.0.9000" to Version.
✔ Adding new heading to NEWS.md.
ℹ There are 2 uncommitted files:
• DESCRIPTION
• NEWS.md
! Is it ok to commit them?

1: For sure
2: Negative
3: Absolutely not

Selection: 2
> cffr::cff_write(r_citation = TRUE)
✔ CITATION.cff generated
══ Validating cff ═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
✔ Congratulations! CITATION.cff is valid
══ Updating inst/CITATION file ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
ℹ Writing 1 entry ...
✔ Results written to ./inst/CITATION
```

which resulted in `CITATION.cff`
```yaml
# --------------------------------------------
# CITATION file created with {cffr} R package
# See also: https://docs.ropensci.org/cffr/
# --------------------------------------------
 
cff-version: 1.2.0
message: 'To cite package "animovement" in publications use:'
type: software
license: MIT
title: 'animovement: An R toolbox for analysing animal movement across space and time'
version: 0.6.0.9000
```

but still `inst/CITATION`:
```bib

bibentry(bibtype = "Misc",
         key = "roaldarbol:2025",
         title = "animovement: An R toolbox for analysing animal movement across space and time.",
         author = person(given = "Mikkel",
                         family = "Roald-Arbøl",
                         email = "trackballr.htmc8@passmail.net",
                         comment = c(ORCID = "0000-0002-9998-0058")),
         year = "2025",
         url = "http://www.roald-arboel.com/animovement/",
         abstract = "An R toolbox for analysing animal movement across space and time.",
         version = "0.6.0")
```
